spring:
  datasource:

    #m每次使用都要改回来username: root
    #    password: password
    username: root
    password: 160125
    url: jdbc:mysql://localhost:3306/ccpedb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml